### ISSUE TITLE
Auto-correct breaks ERB syntax

### ISSUE THREAD

**Issue by jankoegel** [manuelpuyol/vscode-erb-linter#13]
## The Problem
+ when auto correcting the following ERB code (missing space before closing `%>`):

```erb
<div>
  <%= image_tag(image, class: "w-full h-full object-contain")%>
</div>
```
I get the following broken result:
```erb
<div>
  image_tag(image, class: "w-full h-full object-contain")
  %>
  </div>
```

+ Auto correct works correctly on the CLI.
+ do you have any idea what might be causing this?

## My specs
+ `erb_lint (0.5.0)`
+ VSCode `Version: 1.84.2`
+ ERB Linter `v0.0.9`
    ```
    Published
    2021-07-15, 20:00:11
    Last released
    2022-04-14, 20:30:03
    Last updated
    2023-11-14, 00:12:11
    Identifier
    manuelpuyol.erb-linter
    ```
+
   ```json
   "[erb]": {
    "editor.defaultFormatter": "manuelpuyol.erb-linter",
    "editor.formatOnSave": true
    },
    "[html.erb]": {
      "editor.defaultFormatter": "manuelpuyol.erb-linter",
      "editor.formatOnSave": true
    }
    ```

**Comment by jankoegel** [comment]
Sorry, looked at this again today and the problem appeared in the CLI version as well - not sure why it didn't before.

The fix was to add the following recommended Rubocop config to my `.erb-lint.yml` (from https://github.com/Shopify/erb-lint#rubocop):

```yaml
Layout/InitialIndentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
Layout/TrailingEmptyLines:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
Naming/FileName:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
```
